# permissions for end users to edit iscsids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iscsid-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - iscsids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - iscsids/status
  verbs:
  - get
