# permissions for end users to view iscsids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iscsid-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - iscsids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - iscsids/status
  verbs:
  - get
