# permissions for end users to view libvirtds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: libvirtd-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - libvirtds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - libvirtds/status
  verbs:
  - get
