# permissions for end users to edit libvirtds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: libvirtd-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - libvirtds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - libvirtds/status
  verbs:
  - get
