# permissions for end users to view novamigrationtargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novamigrationtarget-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novamigrationtargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novamigrationtargets/status
  verbs:
  - get
