# permissions for end users to view novaexternalcomputes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaexternalcompute-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaexternalcomputes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaexternalcomputes/status
  verbs:
  - get
