# permissions for end users to edit novaexternalcomputes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaexternalcompute-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaexternalcomputes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaexternalcomputes/status
  verbs:
  - get
