# permissions for end users to edit novamigrationtargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novamigrationtarget-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novamigrationtargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novamigrationtargets/status
  verbs:
  - get
