# permissions for end users to view virtlogds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtlogd-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - virtlogds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - virtlogds/status
  verbs:
  - get
