# permissions for end users to edit virtlogds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtlogd-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - virtlogds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - virtlogds/status
  verbs:
  - get
