apiVersion: nova.openstack.org/v1
kind: NovaCompute
metadata:
  name: nova-compute
  namespace: openstack
spec:
  commonConfigMap: common-config
  ospSecrets: osp-secrets
  novaComputeCPUDedicatedSet: 4-7
  novaComputeCPUSharedSet: 0-3

  novaComputeImage: docker.io/tripleotrain/rhel-binary-nova-compute:current-tripleo
  serviceAccount: nova
  roleName: worker-osp
