apiVersion: nova.openstack.org/v1
kind: Virtlogd
metadata:
  name: virtlogd
spec:
  novaLibvirtImage: trunk.registry.rdoproject.org/tripleotrain/rhel-binary-nova-libvirt:f8b48998e5d600f24513848b600e84176ce90223_243bc231
  label: compute
