kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nova-operator
  namespace: openstack
subjects:
- kind: ServiceAccount
  name: nova-operator
roleRef:
  kind: Role
  name: nova-operator
  apiGroup: rbac.authorization.k8s.io
