apiVersion: nova.openstack.org/v1beta1
kind: NovaCompute
metadata:
  name: nova-compute-worker-osp
  namespace: openstack
spec:
  novaComputeCPUDedicatedSet: 4-7
  novaComputeCPUSharedSet: 0-3
  novaComputeImage: docker.io/tripleomaster/centos-binary-nova-compute:current-tripleo
  serviceAccount: nova
  roleName: worker-osp
  cell: cell1
  novaSecret: nova-secret
  placementSecret: placement-secret
  neutronSecret: neutron-secret
  transportURLSecret: nova-cell1-transport-url
