apiVersion: nova.openstack.org/v1beta1
kind: NovaCell
metadata:
  name: novacell1-with-upcall-sample
spec:
  # By having access to the API DB this cell has upcall support
  apiDatabaseHostname: openstack
  cellDatabaseHostname: openstack
  cellMessageBusSecretName: rabbitmq-transport-url-cell1-transport
  cellName: cell1
  conductorServiceTemplate: {}
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  noVNCProxyServiceTemplate: {}
  secret: osp-secret
