apiVersion: nova.openstack.org/v1beta1
kind: NovaConductor
metadata:
  name: novaconductor-sample
spec:
  apiDatabaseHostname: openstack
  cellMessageBusSecretName: rabbitmq-transport-url-nova-api-transport
  cellName: cell0
  containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
