apiVersion: nova.openstack.org/v1beta1
kind: NovaCell
metadata:
  name: novacell2-without-upcall-sample
spec:
  cellDatabaseHostname: openstack
  cellMessageBusSecretName: rabbitmq-transport-url-cell2-transport
  cellName: cell2
  conductorServiceTemplate: {}
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  noVNCProxyServiceTemplate: {}
  secret: osp-secret
